
class AuthException(Exception):
    def __init__(self):
        pass

class ResourceNotFound(Exception):
    def __init__(self):
        pass